import {orderTypeLabel} from './order-types.js';
import {requireCondition as check} from './security.js';
import {buildOrderPdf} from './order-pdf.js';
const CONFIG='order-email-config',INDEX='order-email-jobs',key=id=>'order-email:'+id;
const esc=value=>String(value??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
export function orderEmailConfig(store){return store.read(CONFIG,{enabled:false,recipients:[]});}
export function orderEmailAdmin(store,actor){check(actor.isAdmin,'Admin access required',403);return {ok:true,config:orderEmailConfig(store),providerReady:store.env.EMAIL_ENABLED==='true'&&!!store.env.RESEND_API_KEY&&!!store.env.FROM_EMAIL,jobs:store.read(INDEX,[]).slice(-100).reverse().map(id=>{const job=store.read(key(id));return job?{id:job.id,orderNumber:job.order.orderNumber,project:job.order.project,orderedBy:job.orderedBy,recipients:job.recipients,status:job.status,attempts:job.attempts||0,error:job.error||'',createdAt:job.createdAt,sentAt:job.sentAt||null,providerId:job.providerId||null}:null;}).filter(Boolean)};}
export function saveOrderEmailConfig(store,body,actor){check(actor.isAdmin,'Admin access required',403);check(Array.isArray(body.recipients)&&body.recipients.length<=20,'Enter up to 20 email addresses');const recipients=[...new Set(body.recipients.map(value=>String(value).trim().toLowerCase()))];check(recipients.every(value=>value.length<=254&&/^[^\s@<>;,]+@[^\s@<>;,]+\.[^\s@<>;,]+$/.test(value)),'Enter valid email addresses');const config={enabled:body.enabled===true,recipients};check(!config.enabled||recipients.length>0,'Add at least one recipient before enabling');store.ctx.storage.transactionSync(()=>{store.write(CONFIG,config);store.audit(actor.username,'order-email-settings-updated',config);});return orderEmailAdmin(store,actor);}
export function enqueueOrderEmail(store,order){const config=orderEmailConfig(store);if(!config.enabled||!config.recipients.length)return;if(store.read(key(order.id)))return;const user=store.read('users',{})[order.requestedBy]||{};const displayName=String(user.displayName||order.requestedBy),orderedBy=displayName===order.requestedBy?displayName:`${displayName} (${order.requestedBy})`;store.write(key(order.id),{id:order.id,order:structuredClone(order),orderedBy,recipients:[...config.recipients],createdAt:new Date().toISOString(),status:'queued',attempts:0,nextAttemptAt:0,leaseUntil:0});store.write(INDEX,[...store.read(INDEX,[]),order.id]);}
export function buildOrderEmail(job,from){const order=job.order,rows=order.items.map(item=>`<tr><td style="padding:8px;border-bottom:1px solid #ddd">${esc(item.quantity)}</td><td style="padding:8px;border-bottom:1px solid #ddd">${esc(item.description)}</td></tr>`).join(''),fields=[['Project',order.project],['Ordered by',job.orderedBy],['Order type',orderTypeLabel(order)],['Requested delivery',[order.requestedDeliveryDate,order.requestedDeliveryTime].filter(Boolean).join(' · ')],['Site contact',order.siteContact],['Phone',order.phone],['Location / notes',order.locationNotes]],html=`<div style="font-family:Arial,sans-serif;max-width:720px;color:#163344"><h1>New site order #${esc(order.orderNumber)}</h1>${fields.map(([label,value])=>`<p><strong>${label}:</strong> ${esc(value||'Not provided').replace(/\n/g,'<br>')}</p>`).join('')}<table style="width:100%;border-collapse:collapse"><thead><tr><th align="left">Quantity</th><th align="left">Item</th></tr></thead><tbody>${rows}</tbody></table><p><a href="https://web.panelstockhq.com/">Open PanelStock</a> to view the order and its latest updates.</p><p>This email is a copy of the order when it was created. Requested delivery is not a confirmed delivery date.</p></div>`,pdf=buildOrderPdf({...order,requestedBy:job.orderedBy}),binary=Array.from(pdf,byte=>String.fromCharCode(byte)).join('');return {from,to:job.recipients,subject:`New site order #${order.orderNumber} — ${order.project}`.replace(/[\r\n]/g,' '),html,text:`New site order #${order.orderNumber}\n${fields.map(([label,value])=>label+': '+(value||'Not provided')).join('\n')}\n\n${order.items.map(item=>item.quantity+' × '+item.description).join('\n')}\n\nOpen PanelStock: https://web.panelstockhq.com/`,attachments:[{filename:`Site-Order-${order.orderNumber}.pdf`,content:btoa(binary)}]};}
export async function processOrderEmails(store,fetcher=fetch,now=Date.now()){
 if(store.env.READ_ONLY==='true'||store.env.EMAIL_ENABLED!=='true'||!store.env.RESEND_API_KEY||!store.env.FROM_EMAIL||!orderEmailConfig(store).enabled)return;
 let processed=0;for(const id of store.read(INDEX,[])){if(processed>=3)break;let job=store.read(key(id));if(!job||!['queued','retrying','sending'].includes(job.status)||job.leaseUntil>now||job.nextAttemptAt>now)continue;
 if(job.firstAttemptAt&&now-job.firstAttemptAt>=23*3600000){store.write(key(id),{...job,status:'needs_review',leaseUntil:0,error:'Sending stopped to avoid a duplicate after the safe retry window. Check the email provider before taking further action.'});continue;}
 processed++;job={...job,status:'sending',attempts:(job.attempts||0)+1,firstAttemptAt:job.firstAttemptAt||now,leaseUntil:now+60000,payload:job.payload||buildOrderEmail(job,store.env.FROM_EMAIL)};store.write(key(id),job);
 try{const response=await fetcher('https://api.resend.com/emails',{method:'POST',headers:{Authorization:'Bearer '+store.env.RESEND_API_KEY,'Content-Type':'application/json','Idempotency-Key':'order-created-'+id},body:JSON.stringify(job.payload),signal:AbortSignal.timeout(10000)});const result=await response.json().catch(()=>({}));if(response.ok&&result.id){store.write(key(id),{...job,status:'sent',sentAt:new Date().toISOString(),providerId:String(result.id),leaseUntil:0,error:''});}else{const retry=response.status===429||response.status>=500||response.status===409||response.ok;store.write(key(id),{...job,status:retry?'retrying':'failed',leaseUntil:0,nextAttemptAt:now+15*60000,error:`Email provider ${response.status}. ${retry?'A safe retry is scheduled.':'Check the sender and provider configuration.'}`});}}
 catch{store.write(key(id),{...job,status:'retrying',leaseUntil:0,nextAttemptAt:now+15*60000,error:'Delivery could not be confirmed. A safe retry is scheduled.'});}
 }
}
export function retryOrderEmail(store,body,actor){check(actor.isAdmin,'Admin access required',403);const job=store.read(key(String(body.id||'')));check(job,'Email job not found',404);check(['failed','retrying'].includes(job.status)&&job.leaseUntil<=Date.now(),'This email cannot be retried now',409);check(!job.firstAttemptAt||Date.now()-job.firstAttemptAt<23*3600000,'Safe retry window expired. Check the email provider before taking further action.',409);store.ctx.storage.transactionSync(()=>{store.write(key(job.id),{...job,status:'queued',nextAttemptAt:0,error:''});store.audit(actor.username,'order-email-retry',{orderId:job.id});});return {ok:true};}
