import {brandLogo} from './brand-logo.js';

export function buildScheduleDisplayHtml(token) {
  return `<!doctype html><html lang="en"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><meta name="referrer" content="no-referrer"><title>Daily Schedule — PanelStock</title><style>
*{box-sizing:border-box}html,body{margin:0;max-width:100%;overflow-x:hidden;background:#f8fafc;color:#0f172a;font-family:"Segoe UI",Arial,sans-serif}.screen{width:100%;min-height:100vh;padding:18px 10px}.header{position:relative;min-height:78px;display:grid;place-items:center;margin-bottom:12px}.header img{position:absolute;left:20px;top:0;width:150px;height:64px;object-fit:contain}.date{text-align:center}.date h1{font-size:28px;margin:0}.date p{font-size:14px;color:#64748b;margin:4px 0 0}.status{display:flex;justify-content:space-between;align-items:center;margin:0 14px 12px;color:#64748b;font-size:13px}.dot{display:inline-block;width:8px;height:8px;border-radius:50%;background:#0d9488;margin-right:7px}.timeline-wrap{width:100%;overflow:hidden;border:1px solid #cbd5e1;border-radius:14px;background:#fff}.timeline{width:100%;min-width:0}.timeline-head,.person-row{display:grid;grid-template-columns:clamp(118px,16vw,190px) minmax(0,1fr)}.timeline-head{background:#f8fafc;border-bottom:1px solid #cbd5e1}.person-label{padding:15px clamp(10px,2vw,22px);font-size:12px;font-weight:700;color:#64748b}.hours{display:flex;justify-content:space-between;min-width:0;padding:15px clamp(5px,1vw,14px);color:#64748b;font-size:clamp(9px,1vw,12px);white-space:nowrap}.person-row{border-bottom:1px solid #dbe3ee}.person-row:last-child{border-bottom:0}.person{min-width:0;min-height:82px;display:flex;align-items:center;gap:clamp(6px,1vw,12px);padding:15px clamp(8px,1.5vw,20px);border-right:1px solid #dbe3ee}.person>div:last-child{min-width:0}.avatar{width:clamp(32px,3vw,40px);height:clamp(32px,3vw,40px);display:grid;place-items:center;flex:none;border-radius:50%;background:#cffafe;color:#155e75;font-size:14px;font-weight:800}.person strong,.person small{display:block;overflow:hidden;text-overflow:ellipsis}.person strong{font-size:clamp(11px,1.15vw,14px)}.person small{margin-top:4px;color:#94a3b8;font-size:clamp(9px,1vw,12px);white-space:nowrap}.lane{position:relative;min-width:0;min-height:82px;background-image:linear-gradient(to right,#dbe3ee 1px,transparent 1px)}.entry{position:absolute;top:13px;height:56px;max-width:100%;overflow:hidden;border-radius:9px;background:#3b82c4;color:#fff;padding:9px clamp(6px,1vw,12px);box-shadow:0 1px 2px #0f172a18}.entry.cnc{background:#7c3aed}.entry strong,.entry span{display:block;overflow:hidden;text-overflow:ellipsis;white-space:nowrap}.entry strong{font-size:clamp(10px,1vw,12px)}.entry span{margin-top:3px;font-size:clamp(9px,1vw,12px);color:#ffffffd9}.empty{height:82px}.error{color:#92400e}.footer{margin-top:13px;color:#94a3b8;text-align:center;font-size:12px}@media(max-width:700px){.screen{padding:10px 6px}.header img{left:6px;width:90px;height:44px}.header{min-height:64px}.date h1{font-size:19px}.date p{font-size:12px}.status{margin-inline:5px}.timeline-head,.person-row{grid-template-columns:118px minmax(0,1fr)}.person small{display:none}.entry{padding-inline:5px}}
</style></head><body><main class="screen"><header class="header"><img src="${brandLogo}" alt="Lennox Facades"><div class="date"><h1 id="date"></h1><p>Daily schedule</p></div></header><div class="status"><span id="connection"><i class="dot"></i>Loading latest schedule…</span><strong id="clock"></strong></div><section class="timeline-wrap"><div id="timeline" class="timeline"></div></section><footer class="footer">PanelStock · Read-only TV display · refreshes automatically</footer></main><script>
const TOKEN=${JSON.stringify(token).replace(/</g,'\\u003c')},timeline=document.getElementById('timeline'),connection=document.getElementById('connection');let loaded=false;
const esc=value=>String(value??'').replace(/[&<>"']/g,char=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[char]));
function brisbaneDate(){const parts=new Intl.DateTimeFormat('en-AU',{timeZone:'Australia/Brisbane',year:'numeric',month:'2-digit',day:'2-digit'}).formatToParts(new Date()),get=type=>parts.find(part=>part.type===type).value;return get('year')+'-'+get('month')+'-'+get('day');}
function updateClock(){const now=new Date();document.getElementById('clock').textContent=now.toLocaleTimeString('en-AU',{timeZone:'Australia/Brisbane',hour:'numeric',minute:'2-digit'});document.getElementById('date').textContent=now.toLocaleDateString('en-AU',{timeZone:'Australia/Brisbane',weekday:'long',day:'numeric',month:'long',year:'numeric'});}updateClock();setInterval(updateClock,30000);
const minutes=value=>{const parts=String(value||'').split(':').map(Number);return (parts[0]||0)*60+(parts[1]||0);},hourLabel=hour=>hour>12?(hour-12)+' PM':hour===12?'12 PM':hour+' AM';
function render(data){const today=brisbaneDate(),entries=(data.entries||[]).filter(entry=>entry.date===today),people=data.people||[],start=Number(data.settings?.startHour??6),end=Number(data.settings?.endHour??18),span=Math.max(1,(end-start)*60),hours=Array.from({length:end-start+1},(_,index)=>index+start);timeline.innerHTML='<div class="timeline-head"><div class="person-label">Person</div><div class="hours">'+hours.map(hour=>'<span>'+hourLabel(hour)+'</span>').join('')+'</div></div>'+people.map(person=>{const rows=entries.filter(entry=>entry.assignedUsername===person.username).sort((a,b)=>String(a.startTime||'').localeCompare(String(b.startTime||''))),initials=String(person.displayName||'?').split(/\\s+/).map(part=>part[0]).join('').slice(0,2).toUpperCase(),avatar=person.profilePhoto?'<img src="'+esc(person.profilePhoto)+'" alt="" style="width:100%;height:100%;object-fit:cover">':esc(initials),blocks=rows.map(entry=>{const from=Math.max(start*60,Math.min(end*60,minutes(entry.startTime))),to=Math.max(from+30,Math.min(end*60,minutes(entry.endTime)||(from+60))),left=(from-start*60)/span*100,width=Math.max(4,(to-from)/span*100);return '<div class="entry '+((entry.scheduleType||'general')==='cnc'?'cnc':'')+'" style="left:'+left+'%;width:'+width+'%"><strong>'+esc(entry.startTime||'')+' '+esc(entry.title)+'</strong><span>'+esc(entry.project)+'</span></div>';}).join('');return '<div class="person-row"><div class="person"><div class="avatar" style="overflow:hidden">'+avatar+'</div><div><strong>'+esc(person.displayName)+'</strong><small>'+rows.length+' event'+(rows.length===1?'':'s')+' scheduled</small></div></div><div class="lane" style="background-size:'+(100/Math.max(1,end-start))+'% 100%">'+(blocks||'<div class="empty">No events scheduled</div>')+'</div></div>';}).join('');}
async function refresh(){try{const endpoint=location.hostname==='tv.panelstockhq.com'?'/data?code=':location.hostname==='cnc.panelstockhq.com'?'/tv/data?code=':'/schedule-display/data?token=',response=await fetch(endpoint+encodeURIComponent(TOKEN),{cache:'no-store',signal:AbortSignal.timeout(15000)});if(!response.ok)throw Error();const data=await response.json();render(data);loaded=true;connection.className='';connection.innerHTML='<i class="dot"></i>Updated '+new Date().toLocaleTimeString('en-AU',{timeZone:'Australia/Brisbane',hour:'numeric',minute:'2-digit'});}catch{connection.className='error';connection.textContent=loaded?'Connection lost — showing the last schedule. Retrying…':'Unable to load schedule. Retrying…';}}refresh();setInterval(refresh,30000);
</script></body></html>`;
}
