import {brandLogo} from './brand-logo.js';

export function buildScheduleDisplayHtml(token) {
  return `<!doctype html><html lang="en"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><meta name="referrer" content="no-referrer"><title>Daily Schedule — PanelStock</title><style>
*{box-sizing:border-box}body{margin:0;background:#e8eef1;color:#0f172a;font-family:Calibri,Arial,sans-serif}.screen{min-height:100vh;padding:28px 34px}.header{display:flex;align-items:center;justify-content:space-between;gap:30px;margin-bottom:22px}.header img{width:240px;height:105px;object-fit:contain}.title{text-align:right}.title h1{font-size:34px;margin:0}.title p{font-size:20px;color:#475569;margin:7px 0 0}.status{display:flex;justify-content:space-between;align-items:center;margin-bottom:16px;color:#475569;font-size:16px}.dot{display:inline-block;width:10px;height:10px;border-radius:50%;background:#0d9488;margin-right:8px}.grid{display:grid;grid-template-columns:repeat(auto-fit,minmax(330px,1fr));gap:16px}.person{background:#fff;border:1px solid #cbd5e1;border-radius:16px;overflow:hidden;box-shadow:0 4px 15px #0f172a0d}.person h2{margin:0;padding:15px 18px;background:#0f172a;color:#fff;font-size:23px}.entries{padding:13px}.entry{border-left:8px solid #0284c7;background:#f0f9ff;border-radius:10px;padding:13px 15px;margin-bottom:10px}.entry.cnc{border-color:#7c3aed;background:#f5f3ff}.entry:last-child{margin-bottom:0}.time{font-size:18px;font-weight:700;color:#155e75}.activity{font-size:21px;font-weight:700;margin-top:4px}.project{font-size:17px;color:#475569;margin-top:4px}.empty{padding:28px 18px;color:#94a3b8;text-align:center;font-size:17px}.error{color:#92400e}.footer{margin-top:18px;color:#64748b;text-align:center;font-size:14px}@media(max-width:700px){.screen{padding:18px}.header img{width:170px;height:75px}.title h1{font-size:25px}.title p{font-size:16px}}
</style></head><body><main class="screen"><header class="header"><img src="${brandLogo}" alt="Lennox Facades"><div class="title"><h1>Daily Schedule</h1><p id="date"></p></div></header><div class="status"><span id="connection"><i class="dot"></i>Loading latest schedule…</span><strong id="clock"></strong></div><section id="grid" class="grid"></section><footer class="footer">PanelStock · Read-only TV display · refreshes automatically</footer></main><script>
const TOKEN=${JSON.stringify(token).replace(/</g,'\\u003c')}, grid=document.getElementById('grid'), connection=document.getElementById('connection');let loaded=false;
const esc=value=>String(value??'').replace(/[&<>"']/g,char=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[char]));
function brisbaneDate(){const parts=new Intl.DateTimeFormat('en-AU',{timeZone:'Australia/Brisbane',year:'numeric',month:'2-digit',day:'2-digit'}).formatToParts(new Date()),get=type=>parts.find(part=>part.type===type).value;return get('year')+'-'+get('month')+'-'+get('day');}
function updateClock(){const now=new Date();document.getElementById('clock').textContent=now.toLocaleTimeString('en-AU',{timeZone:'Australia/Brisbane',hour:'numeric',minute:'2-digit'});document.getElementById('date').textContent=now.toLocaleDateString('en-AU',{timeZone:'Australia/Brisbane',weekday:'long',day:'numeric',month:'long',year:'numeric'});}updateClock();setInterval(updateClock,30000);
function render(data){const today=brisbaneDate(),entries=(data.entries||[]).filter(entry=>entry.date===today),people=data.people||[];grid.innerHTML=people.map(person=>{const rows=entries.filter(entry=>entry.assignedUsername===person.username).sort((a,b)=>String(a.startTime||'').localeCompare(String(b.startTime||'')));return '<article class="person"><h2>'+esc(person.displayName)+'</h2><div class="entries">'+(rows.length?rows.map(entry=>'<div class="entry '+((entry.scheduleType||'general')==='cnc'?'cnc':'')+'"><div class="time">'+esc(entry.startTime||'All day')+(entry.endTime?' – '+esc(entry.endTime):'')+'</div><div class="activity">'+esc(entry.title)+'</div><div class="project">'+esc(entry.project)+'</div></div>').join(''):'<div class="empty">No work scheduled</div>')+'</div></article>';}).join('')||'<article class="person"><div class="empty">No people are selected for the schedule.</div></article>';}
async function refresh(){try{const response=await fetch('/schedule-display/data?token='+encodeURIComponent(TOKEN),{cache:'no-store',signal:AbortSignal.timeout(15000)});if(!response.ok)throw Error();const data=await response.json();render(data);loaded=true;connection.className='';connection.innerHTML='<i class="dot"></i>Updated '+new Date().toLocaleTimeString('en-AU',{timeZone:'Australia/Brisbane',hour:'numeric',minute:'2-digit'});}catch{connection.className='error';connection.textContent=loaded?'Connection lost — showing the last schedule. Retrying…':'Unable to load schedule. Retrying…';}}refresh();setInterval(refresh,30000);
</script></body></html>`;
}
