import {test} from 'node:test';
import assert from 'node:assert/strict';
import fs from 'node:fs';
import vm from 'node:vm';
test('mobile bundle parses, uses individual sessions and excludes voided jobs',()=>{
 const html=fs.readFileSync(new URL('../../index.html',import.meta.url),'utf8');
 for(const match of html.matchAll(/<script\b[^>]*>([\s\S]*?)<\/script>/g))if(match[1].trim())new vm.Script(match[1]);
 assert.ok(html.includes('panelstock-client.js'));
 assert.ok(!html.includes('BAKED_SHARED_SECRET'));
 assert.ok(!html.includes('.slice(0, 800)'));
 assert.match(html,/ResizeObserver loop \(\?:limit exceeded\|completed with undelivered notifications\)/);
 assert.match(html,/ResizeObserver loop \(\?:limit exceeded\|completed with undelivered notifications\)/);
 const dispatch=html.slice(html.indexOf('function DispatchTab'),html.indexOf('function DamageTab'));
 assert.match(dispatch,/ItemPicker[^\n]+sortLikeSoh: true/);
 const transfer=html.slice(html.indexOf('function TransferTab('),html.indexOf('function DispatchTab('));
 assert.match(transfer,/ItemPicker/);
 assert.match(transfer,/offcuts:\[\]/);
 assert.match(transfer,/sortLikeSoh:true/);
 assert.match(transfer,/output\.length/);
 assert.match(transfer,/output\.width/);
 assert.doesNotMatch(transfer,/Select size/);
 assert.match(html,/function ScheduleTab\(\)/);
 assert.match(html,/function CncStockPicker/);
 assert.match(html,/placeholder:"Search colour, material, size, SKU…",style:\{paddingLeft:"2\.5rem"\}/);
 assert.match(html,/function CncStockPicker[\s\S]+?sortSohItems=items=>groupByMaterialLargestFirst/);
 const cncTab=html.slice(html.indexOf('function CncTab('),html.indexOf('function SettingsTab('));
 assert.match(cncTab,/function CncTab\([^)]*\) \{\s*const h = import_react\.createElement;/);
 assert.match(cncTab,/" Bulk Entry"/);
 assert.match(cncTab,/" Schedule panel"/);
 assert.doesNotMatch(cncTab,/"Schedule multiple panels"/);
 assert.ok(cncTab.indexOf('" Bulk Entry"') < cncTab.indexOf('title: "CNC tracker"'));
 assert.match(cncTab,/children: "Complete sheet"/);
 assert.doesNotMatch(cncTab,/children: "Complete panel"/);
 assert.match(html,/function CncDimensionBackfill/);
 const backfill=html.slice(html.indexOf('function CncDimensionBackfill'),html.indexOf('function CncTab'));
 assert.match(backfill,/key: group\.key/);
 assert.doesNotMatch(backfill,/\}, group\.key\)/);
 assert.match(html,/Add historical dimensions/);
 assert.match(html,/Original completion dates and users are preserved/);
 assert.match(html,/function ProfilePhotoSettings\(\)/);
 assert.match(html,/signedInProfile\?\.profilePhoto/);
 assert.match(html,/signedInProfile\?\.displayName \|\| username/);
 assert.match(html,/onClick:saveEmail/);
 assert.match(html,/"Email address"/);
 assert.match(html,/children:"Account information"/);
 assert.match(html,/children:"Profile photo"/);
 assert.match(html,/const cropPhoto=/);
 assert.match(html,/children:"Adjust photo"/);
 assert.match(html,/children:"Adjust current photo"/);
 assert.match(html,/border-4 border-slate-300/);
 assert.match(html,/fixed inset-0 z-50 flex flex-col bg-white/);
 assert.match(html,/width:"min\(88vw, 70vh\)"/);
 assert.match(html,/boxShadow:"0 0 0 9999px rgba\(0,0,0,\.5\)"/);
 assert.match(html,/absolute inset-0 rounded-full border-2 border-white/);
 assert.match(html,/Drag to reposition · Pinch to zoom/);
 assert.match(html,/onPointerDown:pointerDown/);
 assert.match(html,/image\.style\.transformOrigin/);
 assert.match(html,/const target=event\.currentTarget,box=target\.getBoundingClientRect\(\)/);
 assert.doesNotMatch(html,/image=event\.currentTarget\.querySelector/);
 assert.match(html,/onWheel:event/);
 const siteApp=fs.readFileSync(new URL('../../site/app.js',import.meta.url),'utf8');
 assert.match(siteApp,/photo-editor-screen/);
 assert.match(siteApp,/photo-crop-guide/);
 assert.match(siteApp,/data-adjust-current/);
 assert.match(siteApp,/Drag to reposition · Pinch or scroll to zoom/);
 assert.match(siteApp,/image\.style\.transformOrigin/);
 const sitePhotoOverlay=siteApp.slice(siteApp.indexOf('function profileEditorOverlay'),siteApp.indexOf('function settingsView'));
 assert.doesNotMatch(sitePhotoOverlay,/data-photo-zoom=/);
 const appPhotoOverlay=html.slice(html.indexOf('if(photo)return'),html.indexOf('return /* @__PURE__ */',html.indexOf('if(photo)return')+20));
 assert.doesNotMatch(appPhotoOverlay,/changeZoom\(-\.1\)/);
 assert.match(html,/Drag to reposition\. Pinch or scroll to zoom\./);
 assert.match(html,/id: "profile", label: "Profile"/);
 assert.match(html,/tab === "profile"/);
 assert.match(html,/function SupportCenter\(\{isAdmin=false\}\)/);
 assert.match(html,/function SupportHeadsetIcon/);
 assert.match(html,/id: "support", label: "Support", icon: SupportHeadsetIcon/);
 assert.match(html,/id: "notifications", label: "Notifications", icon: Bell/);
 assert.match(html,/function NotificationCenter\(\{onOpen\}\)/);
 assert.match(html,/e\(SectionTitle,\{icon:SupportHeadsetIcon,title:"Support"/);
 assert.match(html,/if\(selected\)return e\("div",\{className:"px-4 pt-4"\},e\(SectionTitle/);
 assert.match(html,/function SupportCenter\(\{isAdmin=false\}\) \{\s*const e=import_react\.createElement;/);
 assert.match(html,/id: "support", label: "Support"/);
 assert.match(html,/tab === "support"/);
 assert.match(html,/\/profile/);
 assert.match(html,/function ScheduleCalendarIcon/);
 assert.match(fs.readFileSync(new URL('../src/schedule-display.js',import.meta.url),'utf8'),/Read-only TV display/);
 assert.match(fs.readFileSync(new URL('../src/schedule-display.js',import.meta.url),'utf8'),/timeline-head/);
 assert.match(fs.readFileSync(new URL('../src/schedule-display.js',import.meta.url),'utf8'),/\.timeline\{width:100%;min-width:0\}/);
 assert.match(fs.readFileSync(new URL('../src/schedule-display.js',import.meta.url),'utf8'),/padding:18px clamp\(24px,2vw,38px\) 18px 10px/);
 assert.match(fs.readFileSync(new URL('../src/schedule-display.js',import.meta.url),'utf8'),/\.entry strong\{font-size:clamp\(13px,1\.35vw,17px\)/);
 assert.match(fs.readFileSync(new URL('../src/schedule-display.js',import.meta.url),'utf8'),/\.entry span\{margin-top:5px;font-size:clamp\(12px,1\.2vw,15px\)/);
 assert.match(fs.readFileSync(new URL('../src/schedule-display.js',import.meta.url),'utf8'),/\.entry\.delivery\{background:#ea580c\}/);
 assert.match(fs.readFileSync(new URL('../src/schedule-display.js',import.meta.url),'utf8'),/grid-template-columns:clamp\(132px,17vw,210px\) minmax\(0,1fr\)/);
 assert.doesNotMatch(fs.readFileSync(new URL('../src/schedule-display.js',import.meta.url),'utf8'),/min-width:1050px/);
 assert.match(fs.readFileSync(new URL('../src/schedule-display.js',import.meta.url),'utf8'),/meta name="color-scheme" content="only light"/);
 assert.match(fs.readFileSync(new URL('../src/schedule-display.js',import.meta.url),'utf8'),/html\{color-scheme:only light\}/);
 assert.doesNotMatch(fs.readFileSync(new URL('../src/schedule-display.js',import.meta.url),'utf8'),/id="clock"/);
 assert.match(fs.readFileSync(new URL('../src/schedule-display.js',import.meta.url),'utf8'),/<h1 id="date"><\/h1>/);
 assert.match(html,/Your daily schedule/);
 assert.match(html,/BAKED_WORKER_URL\+"\/schedule"/);
 assert.doesNotMatch(html,/My schedule/);
 assert.doesNotMatch(html,/All schedules/);
 assert.doesNotMatch(html,/Refresh schedule/);
 assert.match(html,/type:"date",value:selectedDate/);
 assert.match(html,/children:"Today"/);
 assert.match(html,/assignedUsername===viewer&&entry\.date===selectedDate/);
 assert.match(html,/id: "transfer", label: "Convert"/);
 assert.match(html,/children: "Material catalogue"/);
 assert.match(html,/children: t\.type === "catalog" \? "catalogue" : t\.type/);
 assert.match(html,/tab === "transfer"/);
 assert.match(html,/primaryIds=new Set\(\["stock","receive","damage","cnc","schedule"\]\)/);
 assert.doesNotMatch(html,/children: "Register"/);
 assert.doesNotMatch(fs.readFileSync(new URL('../../site/app.js',import.meta.url),'utf8'),/data-mode="register"/);
 const filter=html.match(/const dispatches = transactions.filter\(([^;]+)\);/)[1];
 const result=vm.runInNewContext(`transactions.filter(${filter})`,{transactions:[{type:'dispatch',qty:2},{type:'dispatch',qty:5,voided:true}]});
 assert.equal(result.length,1);assert.equal(result[0].qty,2);
});

test('factory app logs in without stock access and selects the first permitted tab',()=>{
 const html=fs.readFileSync(new URL('../../index.html',import.meta.url),'utf8');
 assert.match(html,/setUsername\(user\.username\);setIsAdmin\(user\.isAdmin\);setTaskAccess\(user\.taskAccess\|\|\{\}\)/);
 assert.match(html,/const firstTab=TABS\.find\(item=>item\.tasks\.length===0\|\|user\.isAdmin\|\|item\.tasks\.some/);
 assert.match(html,/const visibleTabs=TABS\.filter\(item=>item\.tasks\.length===0/);
 assert.match(html,/primaryIds=new Set\(\["stock","receive","damage","cnc","schedule"\]\)/);
 assert.match(html,/moreTabs=visibleTabs\.filter\(item=>!primaryIds\.has\(item\.id\)\)/);
 assert.match(html,/BottomNav, \{ tabs:navigationTabs/);
 assert.match(html,/function MoreTab\(\{tabs,onSelect\}\)/);
});
