import {test} from 'node:test';
import assert from 'node:assert/strict';
import fs from 'node:fs';
import vm from 'node:vm';

function readAppBundles(){
 const bundles=[fs.readFileSync(new URL('../../index.html',import.meta.url),'utf8')];
 const desktopUrl=new URL('../../../panelstock-desktop/index.html',import.meta.url);
 if(fs.existsSync(desktopUrl))bundles.push(fs.readFileSync(desktopUrl,'utf8'));
 return bundles;
}
test('production assets are local and obsolete patch workflows stay removed',()=>{
 const root=new URL('../../',import.meta.url);
 const html=fs.readFileSync(new URL('index.html',root),'utf8');
 assert.match(html,/href="tailwind\.css"/);
 assert.doesNotMatch(html,/cdn\.tailwindcss\.com/);
 assert.equal((html.match(/static\.cloudflareinsights\.com\/beacon\.min\.js/g)||[]).length,1);
 assert.ok(fs.statSync(new URL('tailwind.css',root)).size>10000);
 for(const name of ['add-mobile-sync-recovery.yml','mobile-sync-recovery-v2.yml','fix-retry-sync.yml','fix-retry-sync-button.yml','fix-damage-007-photo.yml'])assert.equal(fs.existsSync(new URL('.github/workflows/'+name,root)),false);
 const ignores=fs.readFileSync(new URL('.gitignore',root),'utf8');
 for(const path of ['worker/dist-production/','output/','outputs/','tmp/'])assert.ok(ignores.includes(path));
});
test('both apps expose secured panel and metalwork QA with CNC operator traceability',()=>{
 for(const html of readAppBundles()){
  assert.match(html,/function QaCenter\(/);
  assert.match(html,/BAKED_WORKER_URL\+"\/qa"/);
  assert.match(html,/BAKED_WORKER_URL\+"\/qa\/check"/);
  assert.match(html,/BAKED_WORKER_URL\+"\/qa\/metalwork"/);
  assert.match(html,/Cut by/);
  assert.match(html,/Fabricated by/);
  assert.match(html,/Require a failure photo/);
  assert.match(html,/Require a photo for every QA check/);
  assert.match(html,/QA photo \(required\)/);
  assert.match(html,/"Take photo"/);
  assert.match(html,/capture:"environment"/);
  assert.match(html,/"Choose photo"/);
  assert.match(html,/QA photo preview/);
  assert.match(html,/await processImageFile\(file\)/);
  assert.match(html,/Complete all/);
  assert.match(html,/role:"checkbox"/);
  assert.match(html,/"Add "\+kind\+" check"/);
  assert.match(html,/"Edit "\+kind\+" check "/);
  assert.match(html,/panelChecks:available\.panel/);
  assert.match(html,/removeCheck=\(kind,key\)/);
  assert.match(html,/"Delete "\+label/);
  assert.match(html,/title:"Delete check"/);
  assert.match(html,/Administrator self-approval reason/);
  assert.match(html,/marked Pre-QA and will not block dispatch/);
  assert.match(html,/Replaced · QA approved/);
  assert.match(html,/Recut required/);
  assert.match(html,/Awaiting recut/);
  assert.match(html,/Mark for recut/);
  assert.doesNotMatch(html,/Rework required|Send for rework/);
  assert.match(html,/space-y-2 py-2 pl-6 pr-2 sm:pl-10/);
  assert.match(html,/rounded-lg border border-cyan-100 bg-cyan-50\/40/);
  assert.match(html,/min-h-11[^\n]+hover:bg-cyan-100\/60/);
  assert.match(html,/replacementStatus/);
  assert.match(html,/\/qa\/dispatch/);
  assert.match(html,/function QaSettingsPage\(/);
  assert.match(html,/function CncPanelEdit\(/);
  assert.match(html,/onEditPanel: editCncPanel/);
  assert.match(html,/"aria-label": "Edit panel "/);
  assert.match(html,/\/qa\/settings/);
  assert.match(html,/Inspection checklists/);
  assert.match(html,/Dispatch load requirements/);
  assert.match(html,/role:"switch"/);
  assert.match(html,/"aria-pressed":selected/);
  assert.match(html,/overflow-hidden rounded-xl border border-slate-200 bg-white/);
  assert.match(html,/Dispatch load/);
  assert.match(html,/Vehicle \/ transport company/);
  assert.match(html,/factory\.qa/);
}
const desktop=readAppBundles()[1];
if(desktop){
 assert.match(desktop,/key:"qaGroup",label:"QA"/);
 assert.ok(desktop.indexOf('label:"QA Check"')<desktop.indexOf('label:"QA Settings"'));
 assert.match(desktop,/name:"QA",codes:\["factory\.qa","factory\.qa\.manage","factory\.qa\.dispatch"\]/);
}
});
test('mobile bundle parses, uses individual sessions and excludes voided jobs',()=>{
 const html=fs.readFileSync(new URL('../../index.html',import.meta.url),'utf8');
 for(const match of html.matchAll(/<script\b[^>]*>([\s\S]*?)<\/script>/g))if(match[1].trim())new vm.Script(match[1]);
 assert.ok(html.includes('panelstock-client.js'));
 assert.ok(!html.includes('BAKED_SHARED_SECRET'));
 assert.match(html,/if \(!result\.ok\) \{\s*setPin\(""\);\s*setError\(result\.error \|\| "Login failed\."\)/);
 assert.match(html,/attempts >= 3 && await PanelStock\.confirm/);
 assert.match(html,/\/passcode-reset-request/);
 assert.match(html,/Passcode reset request sent to the administrators\./);
 assert.match(html,/const \[newReasonPhotoOptional, setNewReasonPhotoOptional\] = useState\(false\)/);
 assert.match(html,/onAddReason\(newReason, newReasonPhotoOptional\)/);
 assert.match(html,/selectedReason\?\.photoOptional !== true/);
 assert.match(html,/button:has\(> svg > polyline\[points="3 6 5 6 21 6"\]\) \{ display: grid; place-items: center; border: 0 !important; background: transparent !important; color: #dc2626 !important;/);
 assert.match(html,/\.ps-split-picker-form button:has\([^}]+align-self: end; margin-bottom: 12px;/);
 assert.match(html,/label: photoRequired \?[\s\S]*: "Photo of damage"/);
 assert.match(html,/"aria-hidden": !photoRequired[\s\S]*children: photoRequired \? "At least one photo is required before this can be submitted\." : ""/);
 assert.match(html,/\/admin\/unlock-user/);
 assert.match(html,/children: "Unlock"/);
 assert.match(html,/status\?\.kind !== "ok"[\s\S]*setTimeout\(\(\) => setStatus\(null\), 2600\)/);
 assert.match(html,/fixed bottom-20 left-1\/2 z-50/);
 assert.ok(!html.includes('.slice(0, 800)'));
 assert.match(html,/ResizeObserver loop \(\?:limit exceeded\|completed with undelivered notifications\)/);
 assert.match(html,/ResizeObserver loop \(\?:limit exceeded\|completed with undelivered notifications\)/);
 const dispatch=html.slice(html.indexOf('function DispatchTab'),html.indexOf('function DamageTab'));
 assert.match(dispatch,/ItemPicker[^\n]+sortLikeSoh: true/);
 const transfer=html.slice(html.indexOf('function TransferTab('),html.indexOf('function DispatchTab('));
 assert.match(transfer,/ItemPicker/);
 assert.match(transfer,/offcuts:\[\]/);
 assert.match(transfer,/sortLikeSoh:true/);
 assert.match(transfer,/output\.length/);
 assert.match(transfer,/output\.width/);
 assert.match(transfer,/catalogue material/);
 assert.match(transfer,/disabled:!source/);
 assert.doesNotMatch(transfer,/source&&outputs\.map/);
 assert.doesNotMatch(transfer,/source&&.*Source quantity/);
 assert.doesNotMatch(transfer,/Select size/);
 assert.match(html,/function ScheduleTab\(\)/);
 assert.match(html,/function CncStockPicker/);
 assert.match(html,/\.ps-cnc-row\{grid-template-columns:minmax\(0,\.8fr\) minmax\(0,1fr\) minmax\(0,1\.35fr\) 26px\}/);
 assert.match(html,/placeholder:"Search colour, material, size, SKU…",style:\{paddingLeft:"2\.5rem"\}/);
 assert.match(html,/function CncStockPicker[\s\S]+?sortSohItems=items=>groupByMaterialLargestFirst/);
 const cncPicker=html.slice(html.indexOf('function CncStockPicker'),html.indexOf('function CncSingleForm'));
 assert.match(cncPicker,/children:`\$\{count\} CNC`/);
 assert.doesNotMatch(cncPicker,/reserved for CNC/);
 const cncTab=html.slice(html.indexOf('function CncTab('),html.indexOf('function SettingsTab('));
 assert.match(cncTab,/function CncTab\([^)]*\) \{\s*const h = import_react\.createElement;/);
 assert.doesNotMatch(cncTab,/" Bulk Entry"/);
 assert.doesNotMatch(cncTab,/" Import PDF"/);
 assert.match(html,/function CncPdfImport/);
 assert.match(html,/var Upload = \(p\) =>/);
 const pdfImport=html.slice(html.indexOf('function CncPdfImport'),html.indexOf('function CncDimensionBackfill'));
 assert.match(pdfImport,/"Choose PDF"/);
 assert.match(pdfImport,/className:"ps-entry-primary"/);
 assert.match(pdfImport,/className:"ps-entry-cancel"/);
 assert.match(pdfImport,/onClick:onClose/);
 assert.match(html,/function projectTitleCase\(value\)/);
 assert.match(pdfImport,/jobReference:projectTitleCase\(page\.project\)/);
 assert.match(html,/nth-child\(6\)\{grid-column:2;grid-row:1\/span 5\}/);
 const scheduleTab=html.slice(html.indexOf('function ScheduleTab('),html.indexOf('function JobsTab('));
 assert.doesNotMatch(scheduleTab,/" Import CNC PDF"/);
 assert.match(cncTab,/" Import CNC PDF"[\s\S]+?title: "Schedule CNC panels"/);
 assert.match(cncTab,/CncBulkForm, \{ variants, offcuts, cncPanels,/);
 assert.match(html,/children:"Additional sheets"/);
 assert.match(html,/children:`Sheet \$\{i\+2\}`/);
 assert.doesNotMatch(html,/children:"Additional panels"/);
 assert.doesNotMatch(cncTab,/CncSingleForm, \{ variants, offcuts, cncPanels,/);
 assert.match(html,/\/cnc-pdf\/analyse/);
 assert.match(cncTab,/" Schedule panel"/);
 assert.doesNotMatch(cncTab,/"Schedule multiple panels"/);
 assert.match(cncTab,/onCompleteSheet: view === "pending" \? setSheetToComplete : null/);
 assert.match(html,/Add the proposed off-cut to SOH/);
 assert.doesNotMatch(cncTab,/children: "Complete panel"/);
 assert.match(html,/function CncDimensionBackfill/);
 const backfill=html.slice(html.indexOf('function CncDimensionBackfill'),html.indexOf('function CncTab'));
 assert.match(backfill,/key: group\.key/);
 assert.doesNotMatch(backfill,/\}, group\.key\)/);
 assert.match(html,/Add historical dimensions/);
 assert.match(html,/Original completion dates and users are preserved/);
 assert.match(html,/function ProfilePhotoSettings\(\)/);
 assert.match(html,/signedInProfile\?\.profilePhoto/);
 assert.match(html,/signedInProfile\?\.displayName \|\| username/);
 assert.match(html,/onClick:saveEmail/);
 assert.match(html,/"Email address"/);
 assert.match(html,/children:"Account information"/);
 assert.match(html,/children:"Profile photo"/);
 assert.match(html,/const cropPhoto=/);
 assert.match(html,/children:"Adjust photo"/);
 assert.match(html,/children:"Adjust current photo"/);
 assert.match(html,/border-4 border-slate-300/);
 assert.match(html,/fixed inset-0 z-50 flex flex-col bg-white/);
 assert.match(html,/width:"min\(88vw, 70vh\)"/);
 assert.match(html,/boxShadow:"0 0 0 9999px rgba\(0,0,0,\.5\)"/);
 assert.match(html,/absolute inset-0 rounded-full border-2 border-white/);
 assert.match(html,/Drag to reposition · Pinch to zoom/);
 assert.match(html,/onPointerDown:pointerDown/);
 assert.match(html,/image\.style\.transformOrigin/);
 assert.match(html,/const target=event\.currentTarget,box=target\.getBoundingClientRect\(\)/);
 assert.doesNotMatch(html,/image=event\.currentTarget\.querySelector/);
 assert.match(html,/onWheel:event/);
 const siteApp=fs.readFileSync(new URL('../../site/app.js',import.meta.url),'utf8');
 assert.match(siteApp,/photo-editor-screen/);
 assert.match(siteApp,/photo-crop-guide/);
 assert.match(siteApp,/data-adjust-current/);
 assert.match(siteApp,/Drag to reposition · Pinch or scroll to zoom/);
 assert.match(siteApp,/image\.style\.transformOrigin/);
 const sitePhotoOverlay=siteApp.slice(siteApp.indexOf('function profileEditorOverlay'),siteApp.indexOf('function settingsView'));
 assert.doesNotMatch(sitePhotoOverlay,/data-photo-zoom=/);
 const appPhotoOverlay=html.slice(html.indexOf('if(photo)return'),html.indexOf('return /* @__PURE__ */',html.indexOf('if(photo)return')+20));
 assert.doesNotMatch(appPhotoOverlay,/changeZoom\(-\.1\)/);
 assert.match(html,/Drag to reposition\. Pinch or scroll to zoom\./);
 assert.match(html,/id: "profile", label: "Profile"/);
 assert.match(html,/tab === "profile"/);
 assert.match(html,/function SupportCenter\(\{isAdmin=false\}\)/);
 assert.match(html,/function SupportHeadsetIcon/);
 assert.match(html,/id: "support", label: "Support", icon: SupportHeadsetIcon/);
 assert.match(html,/id: "notifications", label: "Notifications", icon: Bell/);
 assert.match(html,/function NotificationCenter\(\{onOpen,onUnreadChange\}\)/);
 assert.match(html,/\/notifications\/clear/);
 assert.match(html,/Clear notifications/);
 assert.match(html,/onNotifications:\(\)=>setTab\("notifications"\)/);
 assert.match(html,/Bell,\{size:38\}/);
 assert.match(html,/relative block h-\[38px\] w-\[38px\]/);
 assert.match(html,/-right-0\.5 -top-1 grid min-h-\[18px\].*ring-white/);
 assert.doesNotMatch(html,/children: "Notifications"/);
 assert.doesNotMatch(html,/h-14 w-14 place-items-center rounded-full bg-neutral-900\/10/);
 assert.match(html,/notificationCount>99\?"99\+":notificationCount/);
 assert.match(html,/function PushNotificationControl\(\)/);
 assert.match(html,/function NotificationPreferences\(\)/);
 assert.match(html,/\/notification-preferences/);
 assert.match(html,/Schedule notifications/);
 assert.match(html,/CNC scheduling notifications/);
 assert.match(html,/Support notifications/);
 assert.match(html,/Push delivery/);
 assert.match(html,/navigator\.serviceWorker\.register\('\/push-sw\.js'/);
 assert.match(fs.readFileSync(new URL('../../push-sw.js',import.meta.url),'utf8'),/showNotification/);
 assert.doesNotMatch(html,/children: "Scan QR Code"/);
 assert.match(html,/e\(SectionTitle,\{icon:SupportHeadsetIcon,title:"Support"/);
 assert.match(html,/if\(selected\)return e\("div",\{className:"px-4 pt-4"\},e\(SectionTitle/);
 assert.match(html,/function SupportCenter\(\{isAdmin=false\}\) \{\s*const e=import_react\.createElement;/);
 assert.match(html,/id: "support", label: "Support"/);
 assert.match(html,/tab === "support"/);
 assert.match(html,/\/profile/);
 assert.match(html,/function ScheduleCalendarIcon/);
 assert.match(fs.readFileSync(new URL('../src/schedule-display.js',import.meta.url),'utf8'),/Read-only TV display/);
 assert.match(fs.readFileSync(new URL('../src/schedule-display.js',import.meta.url),'utf8'),/timeline-head/);
 assert.match(fs.readFileSync(new URL('../src/schedule-display.js',import.meta.url),'utf8'),/\.timeline\{width:100%;min-width:0\}/);
 assert.match(fs.readFileSync(new URL('../src/schedule-display.js',import.meta.url),'utf8'),/padding:18px clamp\(24px,2vw,38px\) 18px 10px/);
 assert.match(fs.readFileSync(new URL('../src/schedule-display.js',import.meta.url),'utf8'),/\.entry strong\{font-size:clamp\(13px,1\.35vw,17px\)/);
 assert.match(fs.readFileSync(new URL('../src/schedule-display.js',import.meta.url),'utf8'),/\.entry span\{margin-top:5px;font-size:clamp\(12px,1\.2vw,15px\)/);
 assert.match(fs.readFileSync(new URL('../src/schedule-display.js',import.meta.url),'utf8'),/\.entry\.delivery\{background:#ea580c\}/);
 assert.match(fs.readFileSync(new URL('../src/schedule-display.js',import.meta.url),'utf8'),/grid-template-columns:clamp\(132px,17vw,210px\) minmax\(0,1fr\)/);
 assert.doesNotMatch(fs.readFileSync(new URL('../src/schedule-display.js',import.meta.url),'utf8'),/min-width:1050px/);
 assert.match(fs.readFileSync(new URL('../src/schedule-display.js',import.meta.url),'utf8'),/meta name="color-scheme" content="only light"/);
 assert.match(fs.readFileSync(new URL('../src/schedule-display.js',import.meta.url),'utf8'),/html\{color-scheme:only light\}/);
 assert.doesNotMatch(fs.readFileSync(new URL('../src/schedule-display.js',import.meta.url),'utf8'),/id="clock"/);
 assert.match(fs.readFileSync(new URL('../src/schedule-display.js',import.meta.url),'utf8'),/<h1 id="date"><\/h1>/);
 assert.match(html,/Your daily schedule/);
 assert.match(html,/BAKED_WORKER_URL\+"\/schedule"/);
 assert.doesNotMatch(html,/My schedule/);
 assert.doesNotMatch(html,/All schedules/);
 assert.doesNotMatch(html,/Refresh schedule/);
 assert.match(html,/type:"date",value:selectedDate/);
 assert.match(html,/children:"Today"/);
 assert.match(html,/assignedUsername===viewer&&entry\.date===selectedDate/);
 assert.match(html,/id: "transfer", label: "Convert"/);
 assert.match(html,/children: "Material catalogue"/);
 assert.match(html,/item\.type==="catalog"\?"Catalogue":item\.type/);
 assert.match(html,/tab === "transfer"/);
 assert.match(html,/primaryIds=new Set\(\["stock","receive","damage","cnc","qa"\]\)/);
 assert.doesNotMatch(html,/children: "Register"/);
 assert.doesNotMatch(fs.readFileSync(new URL('../../site/app.js',import.meta.url),'utf8'),/data-mode="register"/);
 const filter=html.match(/const dispatches = transactions.filter\(([^;]+)\);/)[1];
 const result=vm.runInNewContext(`transactions.filter(${filter})`,{transactions:[{type:'dispatch',qty:2},{type:'dispatch',qty:5,voided:true}]});
 assert.equal(result.length,1);assert.equal(result[0].qty,2);
});

test('mobile pending changes use IndexedDB with a legacy local-storage migration path',()=>{
 const client=fs.readFileSync(new URL('../../panelstock-client.js',import.meta.url),'utf8');
 assert.match(client,/class IndexedOutboxStorage/);
 assert.match(client,/indexedDB\.open\('panelstock-sync',1\)/);
 assert.match(client,/saved\?\?legacy/);
 assert.match(client,/await this\.storage\.flushWrites\?\.\(\)/);
 assert.match(client,/\/live-ticket/);
 assert.match(client,/panelstock-remote-change/);
});

test('the installed app and last verified session can reopen offline',()=>{
 const client=fs.readFileSync(new URL('../../panelstock-client.js',import.meta.url),'utf8'),worker=fs.readFileSync(new URL('../../push-sw.js',import.meta.url),'utf8');
 assert.match(client,/serviceWorker\.register\('\/push-sw\.js'/);assert.match(client,/await durableStorage\.read\(SESSION\)/);assert.match(client,/Showing the last saved stock view/);
 assert.match(client,/const view=outbox\.snapshot[\s\S]*await durableStorage\.flushWrites\(\)[\s\S]*return view/);
 assert.match(worker,/panelstock-shell-v2/);assert.match(worker,/request\.mode==='navigate'/);assert.match(worker,/cache\.match\(assetUrl\)/);assert.doesNotMatch(worker,/panelstock-reports/);
});

test('app confirmation actions use the PanelStock styled dialog',()=>{
 const html=fs.readFileSync(new URL('../../index.html',import.meta.url),'utf8'),client=fs.readFileSync(new URL('../../panelstock-client.js',import.meta.url),'utf8');
 assert.doesNotMatch(html,/window\.(?:confirm|prompt|alert)\s*\(/);assert.doesNotMatch(client,/(?:window\.)?(?:confirm|prompt|alert)\s*\(/);assert.doesNotMatch(client,/beforeunload/);
 assert.match(client,/role','dialog'/);assert.match(client,/confirm:styledConfirm/);assert.match(client,/showCopy:showCopyDialog/);assert.match(html,/PanelStock\.confirm\(/);
});

test('CNC scheduling checks existing pending and completed panels for duplicates',()=>{
 for(const html of readAppBundles()){assert.match(html,/function cncDuplicateError/);assert.match(html,/cncDuplicateError\(rows,scheduledPanels\)/);assert.match(html,/is already in the CNC tracker/);assert.match(html,/Estimated off-cut/);assert.match(html,/Saved CNC off-cut/);assert.match(html,/Proposed CNC off-cut not saved/);assert.match(html,/offcutDetails:savedOffcut/);}
});

test('administrators have a read-only filtered Audit Centre on web and app',()=>{
 for(const html of readAppBundles()){const end=html.includes('function SettingsPage(')?'function SettingsPage(':'function SettingsTab(';const audit=html.slice(html.indexOf('function AuditCenter('),html.indexOf(end));assert.match(html,/label: "Audit Centre"|label:"Audit Centre"/);assert.match(html,/tab === "audit" && isAdmin/);assert.match(html,/onExportExcel:exportActivityExcel/);assert.match(html,/onExportPDF:exportActivityPDF/);assert.match(audit,/This screen is read-only/);for(const label of ['Search','Action type','User','Status','From date','To date'])assert.match(audit,new RegExp(`"${label}"`));assert.match(audit,/Clear filters/);assert.match(audit,/onClick:onExportExcel/);assert.match(audit,/onClick:onExportPDF/);assert.match(audit,/\["Users",users\.length\]/);assert.match(audit,/"Voided transactions"/);const settings=html.slice(html.indexOf(end));assert.doesNotMatch(settings,/Activity Log|Recent Activity|section === "activity"/);}
});

test('factory app logs in without stock access and selects the first permitted tab',()=>{
 const html=fs.readFileSync(new URL('../../index.html',import.meta.url),'utf8');
 assert.match(html,/setUsername\(user\.username\);setIsAdmin\(user\.isAdmin\);setTaskAccess\(user\.taskAccess\|\|\{\}\)/);
 assert.match(html,/const firstTab=TABS\.find\(item=>\(!item\.adminOnly\|\|user\.isAdmin\).*item\.tasks\.length===0\|\|user\.isAdmin\|\|item\.tasks\.some/);
 assert.match(html,/const visibleTabs=TABS\.filter\(item=>item\.tasks\.length===0/);
 assert.match(html,/primaryIds=new Set\(\["stock","receive","damage","cnc","qa"\]\)/);
 assert.match(html,/moreTabs=visibleTabs\.filter\(item=>!primaryIds\.has\(item\.id\)\)/);
 assert.match(html,/BottomNav, \{ tabs:navigationTabs/);
 assert.match(html,/function MoreTab\(\{tabs,onSelect\}\)/);
});
