import test from 'node:test';import assert from 'node:assert/strict';
import {deliveryIssues,deliveryIssueQueue,updateDeliveryIssue,amendReceipt} from '../src/delivery-issues.js';
import {recordOrderReceipt} from '../src/order-receipts.js';
const actor={username:'manager',isAdmin:true},staff={username:'site',tasks:{'site.orders.view':true,'site.orders.create':true}};
function fixture(){let orders=[{id:'order',project:'Hotel',orderNumber:'1',requestedBy:'site',status:'ordered',updatedAt:'v1',items:[{quantity:5,description:'Panel'}],receipts:[{id:'report',at:'2026-10-01',by:'site',attachmentIds:[],lines:[{index:0,description:'Panel',accepted:2,damaged:2,missing:1}]}]}];const alerts=[],audit=[];const store={read:key=>key==='orders'?structuredClone(orders):{manager:{isAdmin:true},site:{},inactive:{active:false}},write:(key,value)=>orders=value,requireTask:(a,t)=>{if(!a.isAdmin&&!a.tasks?.[t])throw Error('Denied');},taskAccess:()=>({}),ctx:{storage:{transactionSync:fn=>fn()}},notify:(...args)=>alerts.push(args),audit:(...args)=>audit.push(args)};return {store,alerts,audit,get order(){return orders[0]}};}
test('legacy issues can be assigned and replacement receipts close them without double allocation',()=>{const f=fixture();const queue=deliveryIssueQueue(f.store,actor);assert.equal(queue.issues[0].quantity,3);assert.equal(queue.assignees.length,2);const result=updateDeliveryIssue(f.store,'order',{issueId:'report:0',expectedUpdatedAt:'v1',assignedTo:'manager',replacementDate:'2026-10-15',status:'in_progress'},actor);assert.equal(result.order.deliveryIssues[0].assignedTo,'manager');const body={id:crypto.randomUUID(),expectedUpdatedAt:result.order.updatedAt,lines:[{index:0,accepted:3,replacementIssueId:'report:0'}]};const receipt=recordOrderReceipt(f.store,'order',body,actor);assert.equal(deliveryIssues(receipt.order)[0].status,'resolved');assert.equal(deliveryIssues(receipt.order)[0].received,3);assert.ok(f.alerts.some(([,alert])=>alert.title.includes('issue resolved')));recordOrderReceipt(f.store,'order',body,actor);assert.equal(f.order.receipts.length,2);});
test('amendments preserve evidence, retry safely, recalculate issues and require current manager access',()=>{const f=fixture(),body={mutationId:crypto.randomUUID(),receiptId:'report',expectedUpdatedAt:'v1',reason:'Count was transcribed incorrectly',lines:[{index:0,accepted:3,damaged:1,missing:1}]};assert.throws(()=>amendReceipt(f.store,'order',body,staff),/Denied/);const result=amendReceipt(f.store,'order',body,actor);assert.equal(result.order.receipts[0].amendments[0].before[0].accepted,2);assert.equal(result.order.receipts[0].lines[0].accepted,3);assert.equal(result.order.deliveryIssues[0].quantity,2);assert.equal(amendReceipt(f.store,'order',body,actor).duplicate,true);assert.equal(f.audit.length,1);assert.equal(amendReceipt(f.store,'order',{...body,mutationId:crypto.randomUUID()},actor).code,'ORDER_CONFLICT');});
test('invalid issue resolutions, dates, replacement allocations and corrections do not save',()=>{const f=fixture();assert.throws(()=>deliveryIssueQueue(f.store,staff),/Denied/);for(const change of [{status:'resolved'},{replacementDate:'2026-99-99'},{assignedTo:'inactive'}])assert.throws(()=>updateDeliveryIssue(f.store,'order',{issueId:'report:0',expectedUpdatedAt:'v1',...change},actor));assert.throws(()=>recordOrderReceipt(f.store,'order',{id:crypto.randomUUID(),expectedUpdatedAt:'v1',lines:[{index:0,accepted:3,replacementIssueId:'unrelated'}]},staff),/open issue/);assert.throws(()=>amendReceipt(f.store,'order',{mutationId:crypto.randomUUID(),receiptId:'report',expectedUpdatedAt:'v1',reason:'',lines:[{index:0,accepted:9,damaged:0,missing:0}]},actor));assert.equal(f.order.updatedAt,'v1');assert.equal(f.audit.length,0);});
test('corrections cannot invalidate linked replacements and a corrected replacement reopens an issue',()=>{const f=fixture(),received=recordOrderReceipt(f.store,'order',{id:crypto.randomUUID(),expectedUpdatedAt:'v1',lines:[{index:0,accepted:3,replacementIssueId:'report:0'}]},actor);assert.throws(()=>amendReceipt(f.store,'order',{mutationId:crypto.randomUUID(),receiptId:'report',expectedUpdatedAt:received.order.updatedAt,reason:'Reduce issue',lines:[{index:0,accepted:2,damaged:1,missing:1}]},actor),/linked replacement/);const amended=amendReceipt(f.store,'order',{mutationId:crypto.randomUUID(),receiptId:received.receipt.id,expectedUpdatedAt:received.order.updatedAt,reason:'Only two replacements received',lines:[{index:0,accepted:2,damaged:0,missing:0}]},actor);assert.equal(amended.order.deliveryIssues[0].remaining,1);assert.equal(amended.order.deliveryIssues[0].status,'open');});
