import test from 'node:test';
import assert from 'node:assert/strict';
import {orderAttachment} from '../src/order-attachments.js';
const owner={username:'requester',tasks:{'site.orders.view':true,'site.orders.create':true}},orderId='12345678-1234-1234-1234-123456789012';
function fixture(){const docs=new Map([['orders',[{id:orderId,requestedBy:owner.username}]]]),objects=new Map(),audits=[];const store={read:(key,fallback)=>structuredClone(docs.get(key)??fallback),write:(key,value)=>docs.set(key,structuredClone(value)),requireTask:(actor,task)=>{if(!actor.isAdmin&&!actor.tasks?.[task])throw Error('Access denied');},audit:(...args)=>audits.push(args),ctx:{storage:{transactionSync:fn=>fn()}},env:{CAD_PROJECT_FILES:{put:async(key,bytes)=>objects.set(key,bytes),get:async key=>{const bytes=objects.get(key);return bytes?{size:bytes.length,arrayBuffer:async()=>bytes.buffer}:null;},delete:async key=>objects.delete(key)}}};return {store,docs,objects,audits};}
const file=(name='photo.jpg',data='hello')=>({id:crypto.randomUUID(),name,data:btoa(data)});
test('attachments are private, order-linked, downloadable and retry-safe',async()=>{const {store,objects,audits}=fixture(),body=file();const result=await orderAttachment(store,orderId,null,'POST',body,owner);assert.equal(result.attachments.length,1);assert.equal(objects.size,1);assert.equal(result.attachment.size,5);assert.equal(audits.length,1);assert.equal((await orderAttachment(store,orderId,null,'POST',body,owner)).attachments.length,1);const read=await orderAttachment(store,orderId,body.id,'GET',{},owner);assert.equal(atob(read.file.data),'hello');await assert.rejects(orderAttachment(store,'missing',body.id,'GET',{},owner),/Order not found/);await assert.rejects(orderAttachment(store,orderId,crypto.randomUUID(),'GET',{},owner),/Attachment not found/);await assert.rejects(orderAttachment(store,orderId,null,'POST',{...body,data:btoa('different')},owner),/already in use/);});
test('only requester, managers and admins upload; viewing still requires permission',async()=>{const {store,objects}=fixture(),stranger={...owner,username:'someone-else'};await assert.rejects(orderAttachment(store,orderId,null,'POST',file(),stranger),/requester or an order manager/);await assert.rejects(orderAttachment(store,orderId,null,'POST',file(),{username:'requester',tasks:{'site.orders.view':true}}),/Access denied/);assert.equal(objects.size,0);for(const actor of [{username:'manager',tasks:{'site.orders.view':true,'site.orders.manage':true}},{username:'admin',isAdmin:true}])await orderAttachment(store,orderId,null,'POST',file(),actor);await assert.rejects(orderAttachment(store,orderId,null,'GET',{},{}),/Access denied/);});
test('file validation and storage limits are enforced',async()=>{const {store,docs}=fixture();for(const body of [{...file(),data:'!bad'},{...file(),data:''},{...file(),name:'bad\nname'},{...file(),id:'bad'},{...file(),data:'a'.repeat(7*1024*1024)}])await assert.rejects(orderAttachment(store,orderId,null,'POST',body,owner));const orders=docs.get('orders');orders[0].attachments=Array.from({length:10},()=>({id:crypto.randomUUID(),size:1}));await assert.rejects(orderAttachment(store,orderId,null,'POST',file(),owner),/up to 10/);orders[0].attachments=[{id:'large',size:25*1024*1024}];await assert.rejects(orderAttachment(store,orderId,null,'POST',file(),owner),/25 MB/);});
test('large valid files and concurrent uploads keep all metadata',async()=>{const {store,objects}=fixture();const large=file('drawing.pdf','a'.repeat(1024*1024));await orderAttachment(store,orderId,null,'POST',large,owner);await Promise.all([orderAttachment(store,orderId,null,'POST',file('a.txt'),owner),orderAttachment(store,orderId,null,'POST',file('b.txt'),owner)]);assert.equal(store.read('orders')[0].attachments.length,3);assert.equal(objects.size,3);});
