import test from 'node:test';
import assert from 'node:assert/strict';
import {reconcilePanelLoads,panelLoadView,transitionPanelLoad} from '../src/panel-dispatch.js';
const actor={username:'dispatcher'},p={id:'p1',jobReference:'Project',orderNumber:'001',panelNumber:'P1',status:'pending'};
const approved=[{id:'p1',kind:'panel',status:'approved'}];
const dispatch={action:'dispatch',destinationType:'site',destination:'Site address',transport:'Truck',driver:'Alex'};
function ready(){const panels=[{...p,status:'completed'}],load=reconcilePanelLoads([],panels)[0],view=panelLoadView(load,panels,approved);return panelLoadView(transitionPanelLoad(view,{action:'fabricate'},actor),panels,approved);}
test('schedule creates one stable load per project and order, removes cancelled empty loads',()=>{const loads=reconcilePanelLoads([],[p,{...p,id:'p2'}]);assert.equal(loads.length,1);assert.equal(loads[0].panelIds.length,2);assert.deepEqual(reconcilePanelLoads(loads,[p,{...p,id:'p2'}]),loads);assert.equal(reconcilePanelLoads(loads,[]).length,0);});
test('each prerequisite blocks dispatch, including administrator attempts',()=>{const r=ready();for(const field of ['routing','fabricationComplete','qaComplete']){const panels=field==='routing'?[p]:[{...p,status:'completed'}],raw={...r,...(field==='fabricationComplete'?{fabrication:null}:{})},view=panelLoadView(raw,panels,field==='qaComplete'?[]:approved);assert.equal(view.ready,false);assert.throws(()=>transitionPanelLoad(view,dispatch,{...actor,isAdmin:true}),/must all be complete/);}assert.throws(()=>transitionPanelLoad(panelLoadView(reconcilePanelLoads([],[p])[0],[p],[]),{action:'fabricate'},actor),/Complete routing/);});
test('direct site dispatch is final and cannot be duplicated',()=>{const sent=transitionPanelLoad(ready(),dispatch,actor);assert.equal(sent.status,'dispatched_to_site');assert.equal(sent.legs.length,1);assert.throws(()=>transitionPanelLoad(sent,dispatch,actor),/cannot be dispatched again/);});
test('powder coating must complete before a separate site leg',()=>{const r=ready(),sent=transitionPanelLoad(r,{...dispatch,destinationType:'powder_coaters'},actor);assert.equal(sent.status,'at_powder_coaters');assert.throws(()=>transitionPanelLoad(sent,dispatch,actor),/cannot be dispatched again/);const coated=transitionPanelLoad(sent,{action:'coating-complete'},actor),view=panelLoadView(coated,[{...p,status:'completed'}],approved);assert.throws(()=>transitionPanelLoad(view,{...dispatch,destinationType:'powder_coaters'},actor),/must go to site/);const site=transitionPanelLoad(view,dispatch,actor);assert.equal(site.status,'dispatched_to_site');assert.equal(site.legs.length,2);});
test('new panels or edited production invalidate fabrication but never modify a sent manifest',()=>{const r=ready();assert.equal(reconcilePanelLoads([r],[{...p,status:'completed',panelNumber:'Changed'}])[0].fabrication,null);const sent=transitionPanelLoad(r,dispatch,actor),loads=reconcilePanelLoads([sent],[{...p,status:'completed'},{...p,id:'p2'}]);assert.equal(loads.length,2);assert.deepEqual(loads[0].panelIds,['p1']);assert.deepEqual(loads[1].panelIds,['p2']);});
test('legacy dispatched panels are not dispatched twice',()=>{assert.equal(reconcilePanelLoads([],[p],[{lines:[{id:'p1',kind:'panel',quantity:1}]}]).length,0);});
test('failed originals require an approved replacement in the same load',()=>{const panels=[{...p,status:'completed'},{...p,id:'replacement',status:'completed'}],load=reconcilePanelLoads([],panels)[0],records=[{id:'p1',kind:'panel',status:'replaced',replacementId:'replacement'},{id:'replacement',kind:'panel',status:'approved'}];assert.equal(panelLoadView(load,panels,records).qaComplete,true);records[1].status='recut';assert.equal(panelLoadView(load,panels,records).qaComplete,false);});
