import test from 'node:test';
import assert from 'node:assert/strict';
import {connectCncWorkbook,CNC_COLUMNS} from '../src/cnc-excel.js';
import {siteOrdersSheet,siteOrderTextWidth} from '../src/site-orders-excel.js';
test('project, location and notes fit long entries',()=>{const values={Project:'P'.repeat(80),'Location / notes':'A'.repeat(100),Notes:'N'.repeat(90)},sheet=siteOrdersSheet([values],()=> '');for(const [column,key] of [[3,'Project'],[6,'Location / notes'],[15,'Notes']]){const width=Number(sheet.match(new RegExp('<col min="'+column+'" max="'+column+'" width="([^"]+)"'))[1]);assert.ok(width>=siteOrderTextWidth(values[key])+1);assert.ok(width<=siteOrderTextWidth(values[key])+3);}});
test('brand drawing keeps the live query at A2 and embeds the logo',()=>{
 const enc=new TextEncoder(),dec=new TextDecoder();
 const files=Object.entries({'xl/styles.xml':'<styleSheet><fonts count="2"></fonts><cellXfs count="6"></cellXfs></styleSheet>','xl/workbook.xml':'<workbook><sheets><sheet name="Sheet1" sheetId="1" r:id="rId1"/></sheets></workbook>','xl/_rels/workbook.xml.rels':'<Relationships></Relationships>','[Content_Types].xml':'<Types></Types>','xl/worksheets/sheet1.xml':'<worksheet xmlns="http://schemas.openxmlformats.org/spreadsheetml/2006/main"><sheetFormatPr/><cols></cols><sheetData/><pageMargins/></worksheet>'}).map(([name,data])=>({name,data:enc.encode(data)}));
 connectCncWorkbook(files,CNC_COLUMNS,[],'https://example.com/feed',{},[]);
 const text=name=>dec.decode(files.find(f=>f.name===name).data);
 assert.match(text('xl/worksheets/sheet5.xml'),/row r="1" ht="142"/);
 assert.match(text('xl/worksheets/sheet5.xml'),/drawing r:id="rIdBrand"/);
 assert.match(text('xl/workbook.xml'),/Site Orders.*\$A\$2:\$O\$2/);
 assert.match(text('xl/drawings/siteOrdersBrand.xml'),/Site Orders/);
 assert.match(text('xl/drawings/siteOrdersBrand.xml'),/a:pPr algn="ctr"/);
 assert.match(text('xl/drawings/siteOrdersBrand.xml'),/typeface="Segoe UI"/);
 assert.match(text('xl/drawings/siteOrdersBrand.xml'),/sz="3600"/);
 assert.match(text('xl/drawings/siteOrdersBrand.xml'),/anchor="ctr" tIns="0" bIns="0"/);
 assert.match(text('xl/styles.xml'),/vertical="bottom" textRotation="90"/);
 assert.match(text('xl/workbook.xml'),/<sheets><sheet name="Site Orders"[^>]+\/><sheet name="CNC Tracker"/);
 assert.match(text('xl/workbook.xml'),/name="Site_Orders" localSheetId="0"/);
 assert.match(text('xl/workbook.xml'),/name="CNC_Tracker" localSheetId="1"/);
 assert.match(text('xl/worksheets/_rels/sheet5.xml.rels'),/queryTable/);
 assert.match(text('xl/worksheets/_rels/sheet5.xml.rels'),/rIdBrand/);
 assert.equal(files.find(f=>f.name==='xl/media/lennox-logo.png').data[0],137);
 assert.match(text('xl/styles.xml'),/textRotation="90"/);
 assert.match(text('xl/queryTables/queryTable5.xml'),/adjustColumnWidth="0"/);
 assert.match(text('xl/queryTables/queryTable1.xml'),/adjustColumnWidth="0"/);
});

